[package]
name = "bake-assets"
version = "0.1.0"
edition = "2024"

[dependencies]
brg_core = {workspace = true}
anyhow = {workspace = true}
strum = {workspace = true}
serde = {workspace = true }
ron = {workspace = true }