[package]
name = "brg_fundamental"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {workspace = true}
brg_core = {workspace = true}
brg_scene = {workspace = true}
strum = {workspace = true}
auto-impl-ops = {workspace = true}