unstable_features = true
reorder_imports = true
reorder_modules = true
imports_layout = "HorizontalVertical"
imports_granularity = "One"
group_imports = "StdExternalCrate"
empty_item_single_line = false
enum_discrim_align_threshold = 200
struct_field_align_threshold = 200
