[package]
name = "brg_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.0", features = ["dynamic_linking"] }
bevy-inspector-egui = { version = "0.28.0" }
iyes_perf_ui = { git="https://github.com/IyesGames/iyes_perf_ui.git", branch = "main" }