[package]
name = "brg_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {workspace = true}
bevy-inspector-egui = {workspace = true}
iyes_perf_ui = {workspace = true}
strum = {workspace = true}