[package]
name = "brg_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {workspace = true}
auto-impl-ops = {workspace = true}
rand_chacha = {workspace = true}
dirs = {workspace = true}
serde = {workspace = true}
anyhow = {workspace = true}
strum = {workspace = true}